<?php

namespace Database\Seeders;

use App\Models\Article;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Carbon\Carbon;

class ArticleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $articles = [
            [
                'title' => 'Tips Investasi Emas untuk Pemula',
                'slug' => 'tips-investasi-emas-untuk-pemula',
                'excerpt' => 'Pelajari cara memulai investasi emas dengan benar. Panduan lengkap untuk pemula yang ingin mulai menabung emas.',
                'content' => 'Investasi emas merupakan salah satu cara terbaik untuk melindungi kekayaan dari inflasi. Emas memiliki nilai yang stabil dan cenderung naik dalam jangka panjang. Untuk pemula, mulailah dengan investasi kecil dan konsisten setiap bulan. Pilih waktu yang tepat untuk membeli emas, biasanya saat harga sedang turun atau stabil.',
                'image' => 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=400&fit=crop',
                'author' => 'Admin Tabung Emas',
                'status' => 'published',
                'is_featured' => true,
                'views' => 1250,
                'published_at' => Carbon::now()->subDays(5),
            ],
            [
                'title' => 'Mengapa Emas Menjadi Investasi yang Aman?',
                'slug' => 'mengapa-emas-menjadi-investasi-yang-aman',
                'excerpt' => 'Emas telah menjadi pilihan investasi yang aman selama ribuan tahun. Pelajari alasan mengapa emas tetap menjadi favorit investor.',
                'content' => 'Emas memiliki karakteristik unik yang membuatnya menjadi investasi yang aman. Emas tidak dapat dicetak seperti uang kertas, sehingga nilainya tetap terjaga. Selain itu, emas juga memiliki likuiditas tinggi dan dapat dijual kapan saja. Emas juga tidak terpengaruh oleh inflasi dan fluktuasi mata uang.',
                'image' => 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&h=400&fit=crop',
                'author' => 'Tim Analis',
                'status' => 'published',
                'is_featured' => true,
                'views' => 980,
                'published_at' => Carbon::now()->subDays(3),
            ],
            [
                'title' => 'Cara Menghitung Keuntungan Investasi Emas',
                'slug' => 'cara-menghitung-keuntungan-investasi-emas',
                'excerpt' => 'Pelajari cara menghitung keuntungan dari investasi emas Anda. Panduan praktis untuk menghitung ROI investasi emas.',
                'content' => 'Menghitung keuntungan investasi emas relatif sederhana. Anda perlu mengetahui harga beli dan harga jual saat ini. Selisih antara keduanya adalah keuntungan atau kerugian Anda. Jangan lupa untuk memperhitungkan biaya transaksi dan pajak jika ada.',
                'image' => 'https://images.unsplash.com/photo-1606166188517-5ad47ea5e0a0?w=800&h=400&fit=crop',
                'author' => 'Admin Tabung Emas',
                'status' => 'published',
                'is_featured' => false,
                'views' => 756,
                'published_at' => Carbon::now()->subDays(7),
            ],
            [
                'title' => 'Strategi DCA (Dollar Cost Averaging) untuk Investasi Emas',
                'slug' => 'strategi-dca-untuk-investasi-emas',
                'excerpt' => 'Strategi DCA adalah cara terbaik untuk investasi emas jangka panjang. Pelajari bagaimana menerapkan strategi ini.',
                'content' => 'Dollar Cost Averaging (DCA) adalah strategi investasi dimana Anda membeli emas secara rutin dengan jumlah yang sama setiap bulan. Strategi ini membantu mengurangi risiko timing dan membuat investasi lebih terencana. Dengan DCA, Anda tidak perlu khawatir tentang timing yang tepat.',
                'image' => 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=400&fit=crop',
                'author' => 'Tim Analis',
                'status' => 'published',
                'is_featured' => false,
                'views' => 642,
                'published_at' => Carbon::now()->subDays(10),
            ],
            [
                'title' => 'Perbandingan Investasi Emas vs Deposito',
                'slug' => 'perbandingan-investasi-emas-vs-deposito',
                'excerpt' => 'Mana yang lebih menguntungkan: investasi emas atau deposito? Simak perbandingan lengkapnya di artikel ini.',
                'content' => 'Baik emas maupun deposito memiliki kelebihan masing-masing. Emas lebih cocok untuk jangka panjang dan perlindungan dari inflasi, sementara deposito memberikan return yang pasti namun lebih rendah. Kombinasi keduanya adalah strategi yang baik untuk diversifikasi portofolio.',
                'image' => 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&h=400&fit=crop',
                'author' => 'Admin Tabung Emas',
                'status' => 'published',
                'is_featured' => false,
                'views' => 523,
                'published_at' => Carbon::now()->subDays(12),
            ],
            [
                'title' => 'Panduan Lengkap Tabungan Emas Digital',
                'slug' => 'panduan-lengkap-tabungan-emas-digital',
                'excerpt' => 'Tabungan emas digital memudahkan Anda untuk investasi emas kapan saja dan di mana saja. Pelajari cara menggunakannya.',
                'content' => 'Tabungan emas digital adalah solusi modern untuk investasi emas. Anda dapat membeli, menjual, dan memantau tabungan emas Anda melalui aplikasi atau website. Prosesnya cepat, mudah, dan transparan. Semua transaksi tercatat dengan jelas dan dapat diakses kapan saja.',
                'image' => 'https://images.unsplash.com/photo-1606166188517-5ad47ea5e0a0?w=800&h=400&fit=crop',
                'author' => 'Tim Teknologi',
                'status' => 'published',
                'is_featured' => true,
                'views' => 1890,
                'published_at' => Carbon::now()->subDays(1),
            ],
            [
                'title' => 'Faktor-Faktor yang Mempengaruhi Harga Emas',
                'slug' => 'faktor-faktor-yang-mempengaruhi-harga-emas',
                'excerpt' => 'Pahami faktor-faktor ekonomi dan politik yang mempengaruhi pergerakan harga emas di pasar global.',
                'content' => 'Harga emas dipengaruhi oleh berbagai faktor seperti inflasi, suku bunga, nilai tukar dollar AS, kondisi ekonomi global, dan ketidakpastian geopolitik. Memahami faktor-faktor ini akan membantu Anda membuat keputusan investasi yang lebih baik.',
                'image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=400&fit=crop',
                'author' => 'Tim Analis',
                'status' => 'published',
                'is_featured' => false,
                'views' => 890,
                'published_at' => Carbon::now()->subDays(8),
            ],
            [
                'title' => 'Cara Menyimpan Emas dengan Aman',
                'slug' => 'cara-menyimpan-emas-dengan-aman',
                'excerpt' => 'Tips penting untuk menyimpan emas fisik dengan aman di rumah atau menggunakan jasa penyimpanan profesional.',
                'content' => 'Jika Anda memiliki emas fisik, penting untuk menyimpannya dengan aman. Pilih tempat yang aman seperti safe deposit box atau gunakan jasa penyimpanan profesional. Jangan simpan emas di tempat yang mudah ditemukan atau diakses oleh orang lain.',
                'image' => 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop',
                'author' => 'Admin Tabung Emas',
                'status' => 'published',
                'is_featured' => false,
                'views' => 654,
                'published_at' => Carbon::now()->subDays(14),
            ],
            [
                'title' => 'Investasi Emas untuk Dana Pendidikan Anak',
                'slug' => 'investasi-emas-untuk-dana-pendidikan-anak',
                'excerpt' => 'Rencanakan dana pendidikan anak dengan investasi emas jangka panjang. Strategi yang terbukti efektif.',
                'content' => 'Investasi emas adalah pilihan yang tepat untuk dana pendidikan anak. Dengan investasi rutin sejak dini, Anda dapat mengumpulkan dana yang cukup untuk pendidikan anak di masa depan. Emas memberikan perlindungan dari inflasi dan cenderung naik dalam jangka panjang.',
                'image' => 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=400&fit=crop',
                'author' => 'Tim Edukasi',
                'status' => 'published',
                'is_featured' => true,
                'views' => 1120,
                'published_at' => Carbon::now()->subDays(6),
            ],
            [
                'title' => 'Analisis Trend Harga Emas 2024',
                'slug' => 'analisis-trend-harga-emas-2024',
                'excerpt' => 'Analisis mendalam tentang pergerakan harga emas sepanjang tahun 2024 dan prediksi untuk tahun depan.',
                'content' => 'Tahun 2024 menunjukkan volatilitas yang tinggi dalam harga emas. Faktor-faktor seperti inflasi global, kebijakan moneter bank sentral, dan ketegangan geopolitik mempengaruhi pergerakan harga. Analis memprediksi harga emas akan terus menunjukkan tren naik dalam jangka panjang.',
                'image' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=400&fit=crop',
                'author' => 'Tim Analis',
                'status' => 'published',
                'is_featured' => true,
                'views' => 1456,
                'published_at' => Carbon::now()->subDays(2),
            ],
            [
                'title' => 'Keuntungan dan Kerugian Investasi Emas',
                'slug' => 'keuntungan-dan-kerugian-investasi-emas',
                'excerpt' => 'Pelajari keuntungan dan kerugian investasi emas sebelum memutuskan untuk berinvestasi.',
                'content' => 'Investasi emas memiliki keuntungan seperti perlindungan dari inflasi, likuiditas tinggi, dan nilai yang stabil. Namun, emas juga memiliki kerugian seperti tidak memberikan dividen, biaya penyimpanan, dan volatilitas harga jangka pendek. Pahami kedua sisi sebelum berinvestasi.',
                'image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=400&fit=crop',
                'author' => 'Admin Tabung Emas',
                'status' => 'published',
                'is_featured' => false,
                'views' => 789,
                'published_at' => Carbon::now()->subDays(15),
            ],
            [
                'title' => 'Cara Membaca Grafik Harga Emas',
                'slug' => 'cara-membaca-grafik-harga-emas',
                'excerpt' => 'Panduan lengkap untuk membaca dan menganalisis grafik harga emas untuk membantu keputusan investasi.',
                'content' => 'Membaca grafik harga emas memerlukan pemahaman tentang berbagai indikator teknis seperti moving average, support dan resistance level, serta pola grafik. Artikel ini akan mengajarkan Anda dasar-dasar analisis teknis untuk emas.',
                'image' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=400&fit=crop',
                'author' => 'Tim Analis',
                'status' => 'published',
                'is_featured' => false,
                'views' => 567,
                'published_at' => Carbon::now()->subDays(18),
            ],
            [
                'title' => 'Tips Menghindari Penipuan Investasi Emas',
                'slug' => 'tips-menghindari-penipuan-investasi-emas',
                'excerpt' => 'Waspada terhadap penipuan investasi emas. Pelajari cara mengenali dan menghindari investasi emas palsu.',
                'content' => 'Penipuan investasi emas semakin marak. Waspadai tawaran yang terlalu bagus untuk menjadi kenyataan, perusahaan yang tidak terdaftar, dan tekanan untuk investasi cepat. Selalu verifikasi legalitas perusahaan dan gunakan platform yang terpercaya.',
                'image' => 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop',
                'author' => 'Tim Keamanan',
                'status' => 'published',
                'is_featured' => false,
                'views' => 923,
                'published_at' => Carbon::now()->subDays(11),
            ],
            [
                'title' => 'Investasi Emas vs Cryptocurrency: Mana yang Lebih Baik?',
                'slug' => 'investasi-emas-vs-cryptocurrency',
                'excerpt' => 'Perbandingan mendalam antara investasi emas tradisional dan cryptocurrency sebagai instrumen investasi modern.',
                'content' => 'Emas dan cryptocurrency memiliki karakteristik yang berbeda. Emas lebih stabil dan teruji selama ribuan tahun, sementara cryptocurrency lebih volatil namun memiliki potensi pertumbuhan tinggi. Kombinasi keduanya bisa menjadi strategi diversifikasi yang baik.',
                'image' => 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&h=400&fit=crop',
                'author' => 'Tim Analis',
                'status' => 'published',
                'is_featured' => true,
                'views' => 1345,
                'published_at' => Carbon::now()->subDays(4),
            ],
            [
                'title' => 'Program Tabungan Emas untuk Karyawan',
                'slug' => 'program-tabungan-emas-untuk-karyawan',
                'excerpt' => 'Program khusus untuk karyawan perusahaan yang ingin mulai investasi emas dengan potongan gaji otomatis.',
                'content' => 'Program tabungan emas untuk karyawan memungkinkan Anda menabung emas secara otomatis melalui potongan gaji. Program ini memudahkan investasi rutin tanpa perlu ingat untuk transfer manual setiap bulan.',
                'image' => 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&h=400&fit=crop',
                'author' => 'Tim Corporate',
                'status' => 'published',
                'is_featured' => false,
                'views' => 678,
                'published_at' => Carbon::now()->subDays(16),
            ],
            [
                'title' => 'Cara Memilih Emas yang Berkualitas',
                'slug' => 'cara-memilih-emas-yang-berkualitas',
                'excerpt' => 'Panduan lengkap untuk memilih emas dengan kualitas terbaik. Pelajari cara membedakan emas asli dan palsu.',
                'content' => 'Memilih emas berkualitas penting untuk investasi. Perhatikan kadar emas (karat), sertifikat keaslian, dan reputasi penjual. Emas dengan kadar tinggi (24 karat) lebih murni namun lebih lunak. Pilih sesuai kebutuhan investasi Anda.',
                'image' => 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=400&fit=crop',
                'author' => 'Admin Tabung Emas',
                'status' => 'published',
                'is_featured' => false,
                'views' => 834,
                'published_at' => Carbon::now()->subDays(19),
            ],
            [
                'title' => 'Rencana Keuangan dengan Tabungan Emas',
                'slug' => 'rencana-keuangan-dengan-tabungan-emas',
                'excerpt' => 'Bagaimana mengintegrasikan tabungan emas ke dalam rencana keuangan jangka panjang Anda.',
                'content' => 'Tabungan emas dapat menjadi bagian penting dari portofolio keuangan Anda. Alokasikan 10-20% dari portofolio untuk emas sebagai diversifikasi. Rencanakan investasi jangka panjang minimal 5 tahun untuk hasil optimal.',
                'image' => 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop',
                'author' => 'Tim Financial Planning',
                'status' => 'published',
                'is_featured' => false,
                'views' => 712,
                'published_at' => Carbon::now()->subDays(20),
            ],
            [
                'title' => 'Update Harga Emas: Kenaikan Signifikan Minggu Ini',
                'slug' => 'update-harga-emas-kenaikan-signifikan',
                'excerpt' => 'Harga emas mengalami kenaikan signifikan minggu ini. Simak analisis lengkap tentang faktor penyebabnya.',
                'content' => 'Harga emas mengalami kenaikan hingga 3% minggu ini akibat ketidakpastian ekonomi global dan inflasi yang tinggi. Analis memprediksi tren naik akan berlanjut dalam beberapa minggu ke depan. Ini adalah waktu yang baik untuk mulai investasi emas.',
                'image' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=400&fit=crop',
                'author' => 'Tim Analis',
                'status' => 'published',
                'is_featured' => true,
                'views' => 2100,
                'published_at' => Carbon::now()->subHours(12),
            ],
            [
                'title' => 'Testimoni Nasabah: Sukses dengan Tabungan Emas',
                'slug' => 'testimoni-nasabah-sukses-tabungan-emas',
                'excerpt' => 'Kisah sukses nasabah yang berhasil mencapai tujuan keuangan melalui tabungan emas rutin.',
                'content' => 'Banyak nasabah yang berhasil mencapai tujuan keuangan mereka melalui tabungan emas. Mulai dari dana pendidikan, dana pensiun, hingga dana darurat. Konsistensi adalah kunci kesuksesan investasi emas.',
                'image' => 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&h=400&fit=crop',
                'author' => 'Tim Marketing',
                'status' => 'published',
                'is_featured' => false,
                'views' => 445,
                'published_at' => Carbon::now()->subDays(21),
            ],
        ];

        foreach ($articles as $article) {
            Article::firstOrCreate(
                ['slug' => $article['slug']],
                $article
            );
        }
    }
}
